# Generated by Django 4.1 on 2024-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_lead_address_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
